[parameters]
sampling_method = "2"
sample_rate = 600000000
signal_width = 1e-8
plot_opt = 2
plot_time_min = 0.0
plot_time_max = 1.3e-6
plot_fre_min = 0
plot_fre_max = 2000000
simulated_data = "out.root"
TOF = 147